
import { motion } from "framer-motion";
import { ClipboardCheck, Activity, TrendingUp, Zap, Target, Flame } from "lucide-react";
import { cn } from "@/lib/utils";

export const DashboardMetrics = ({
    assessmentCount,
    deficiencyCount,
    healthScore,
    riskLevel
}: {
    assessmentCount: number;
    deficiencyCount: number;
    healthScore: number;
    riskLevel: string;
}) => {
    const metrics = [
        {
            label: "Vitality Index",
            value: `${healthScore}%`,
            icon: Activity,
            color: "text-violet-400",
            bg: "bg-violet-500/10",
            border: "border-violet-500/20",
            trend: "+2.4%",
            trendUp: true,
            description: "Overall biological optimization score."
        },
        {
            label: "Active Streak",
            value: "12 Days",
            icon: Flame,
            color: "text-orange-400",
            bg: "bg-orange-500/10",
            border: "border-orange-500/20",
            trend: "Personal Best",
            trendUp: true,
            description: "Consecutive days of nutrient adherence."
        },
        {
            label: "Biomarker Risk",
            value: riskLevel === "N/A" ? "Calculating" : riskLevel,
            icon: Target,
            color: riskLevel === "High" ? "text-red-400" : riskLevel === "Moderate" ? "text-amber-400" : "text-emerald-400",
            bg: riskLevel === "High" ? "bg-red-500/10" : riskLevel === "Moderate" ? "bg-amber-500/10" : "bg-emerald-500/10",
            border: riskLevel === "High" ? "border-red-500/20" : riskLevel === "Moderate" ? "border-amber-500/20" : "border-emerald-500/20",
            trend: "Last 7d",
            trendUp: false,
            description: "Aggregate probability of nutrient gaps."
        },
        {
            label: "Assessments",
            value: assessmentCount,
            icon: ClipboardCheck,
            color: "text-blue-400",
            bg: "bg-blue-500/10",
            border: "border-blue-500/20",
            trend: "Next in 4d",
            trendUp: true,
            description: "Clinical profiles generated by Vitamin AI."
        }
    ];

    return (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
            {metrics.map((metric, i) => (
                <motion.div
                    key={metric.label}
                    initial={{ opacity: 0, y: 20 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ duration: 0.5, delay: i * 0.1 }}
                    whileHover={{ y: -8 }}
                    className="glass-layer-1 rounded-[2rem] p-8 space-y-6 relative overflow-hidden group hover:glass-layer-2 transition-all duration-500"
                >
                    <div className="flex justify-between items-start">
                        <div className={cn("w-14 h-14 rounded-2xl flex items-center justify-center border shadow-inner transition-all group-hover:scale-110", metric.bg, metric.border)}>
                            <metric.icon className={cn("w-7 h-7", metric.color)} />
                        </div>
                        <div className={cn("px-3 py-1.5 rounded-full text-[10px] font-black uppercase tracking-widest", metric.bg, metric.color)}>
                            {metric.trend}
                        </div>
                    </div>

                    <div className="space-y-1">
                        <p className="text-slate-500 text-[10px] font-bold uppercase tracking-widest">{metric.label}</p>
                        <h3 className="text-4xl font-black text-white tracking-tight leading-none">
                            {metric.value}
                        </h3>
                    </div>

                    <p className="text-slate-500 text-xs leading-relaxed">
                        {metric.description}
                    </p>

                    {/* Subtle Neural Line Decorative */}
                    <div className="absolute bottom-0 left-0 right-0 h-1 bg-gradient-to-r from-transparent via-white/5 to-transparent opacity-0 group-hover:opacity-100 transition-opacity" />
                </motion.div>
            ))}
        </div>
    );
};
